// engram.pull.test.mjs — unit tests for pullMemory() and importMemory() (issue #59).
//
// Acceptance criteria:
//
//   pullMemory():
//   (a) pull → import, in order (the manifest-churn-discard step this used
//       to run first is retired — #955, R6 — there is no writer left to
//       discard churn from).
//   (c) failing git pull → error is propagated and import is NOT called.
//   (f) reindex parity (issue #361) — pullMemory rebuilds the index BETWEEN
//       git pull and import, unconditionally, exactly like
//       plainfiles.pull()'s `_gitPull` → `_rebuildIndex` order
//       (plainfiles.pull.test.mjs, #574). Before this pair of tests, Step 3
//       of pullMemory (added by #574, a029ed0a) had no test that died if it
//       were removed — see reindex-parity.test.mjs for the cross-backend pin.
//   (g) reindex runs even on a no-op pull (nothing changed) — this is the
//       property issue #361 asked for on the `pull` verb: unconditional,
//       never gated on "did anything get imported".
//
//   importMemory():
//   (d) importMemory is exported as a callable function.
//   (e) pullMemory delegates its import step to importMemory by default
//       (default _import seam === importMemory).
//
// All seams are injected so no real git/engram subprocess is spawned, and
// every test below passes an explicit `root` + `_rebuildIndex` seam so the
// REAL `.memory/index.jsonl` of whichever checkout runs this suite is never
// touched.
//
// #1026: the claim that used to sit here — "tests (a)-(c)/(e) rely on the
// production `_rebuildIndex` default against the real repoRoot — deliberately
// left as-is, pre-existing and out of #361's scope" — was NOT verified and
// was wrong in a way that mattered: empirically (mtime + content snapshot,
// isolated per test via `--test-name-pattern`), only (a) and (e) actually
// reach the real repoRoot default; (c) throws in `_gitPull` before the
// `_rebuildIndex` step is ever reached, so it never touched the real root
// despite omitting `root`. All of (a)/(c)/(e) now inject `root` +
// `_rebuildIndex` anyway — (c) for defense-in-depth, so a future reordering
// of pullMemory()'s steps cannot silently start writing to the real root
// again without this file's own before/after guard catching it.
//
// Assertions are on the call log and thrown errors.

import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Real-root-unchanged guard (#1026, same class as #1013/#1022): this file
// sits in the same directory as engram.mjs, so it computes repoRoot the
// SAME way engram.mjs's own `root = repoRoot` default does — snapshot the
// real `.memory/index.jsonl` before any test in this file runs, and assert
// it is byte-for-byte AND mtime unchanged after all of them do.
//
// Content alone is NOT a sufficient signal on this repo today: rebuildIndex()
// regenerates index.jsonl deterministically from `.memory/records/`, and on
// a checkout where the index is already fully in sync with its records (the
// common case), a stray write reproduces byte-identical content — the write
// still happens (a real fs.writeFileSync against the real root), it is just
// invisible to a content-only diff. mtime is included because it catches
// that write regardless of whether the regenerated bytes happen to match.
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../../../../..');
const realIndexPath = join(repoRoot, '.memory', 'index.jsonl');

let realIndexBefore;

before(() => {
  realIndexBefore = {
    content: readFileSync(realIndexPath, 'utf8'),
    mtimeMs: statSync(realIndexPath).mtimeMs,
  };
});

after(() => {
  const content = readFileSync(realIndexPath, 'utf8');
  const mtimeMs = statSync(realIndexPath).mtimeMs;
  assert.equal(
    content,
    realIndexBefore.content,
    '#1026: this file must leave the REAL .memory/index.jsonl content byte-for-byte unchanged — a test reached pullMemory()\'s production repoRoot default',
  );
  assert.equal(
    mtimeMs,
    realIndexBefore.mtimeMs,
    '#1026: this file must never WRITE the REAL .memory/index.jsonl at all — mtime changed even though content matched (rebuildIndex regenerated identical bytes), meaning some test still reached the real repoRoot default',
  );
});

// RED: importMemory import fails until it is exported from engram.mjs.
import { pullMemory, importMemory } from './engram.mjs';

// ---------------------------------------------------------------------------
// pullMemory (a) pull → import, in order
// ---------------------------------------------------------------------------

test('pullMemory: pull → import in order', async () => {
  const callLog = [];

  await pullMemory({
    root: '/fake/root',
    _gitPull: () => { callLog.push('pull'); },
    _rebuildIndex: () => ({ count: 0 }),
    _import:  () => { callLog.push('import'); },
  });

  assert.deepEqual(
    callLog,
    ['pull', 'import'],
    `expected ['pull','import'], got ${JSON.stringify(callLog)}`,
  );
});

test('#1116: pullMemory hands its own root to the import, so the session directory is the pulled tree', async () => {
  let seen;
  await pullMemory({
    root: '/fake/root',
    _gitPull: () => {},
    _rebuildIndex: () => ({ count: 0 }),
    _import: (opts) => { seen = opts?.root; },
  });
  assert.equal(seen, '/fake/root', 'a root override that stops at the pull hydrates engram with the wrong directory');
});

// ---------------------------------------------------------------------------
// pullMemory (c) failing git pull → error propagated, import NOT called
// ---------------------------------------------------------------------------

test('pullMemory: failing git pull propagates error and skips import', async () => {
  let importCalled = false;

  await assert.rejects(
    () => pullMemory({
      root: '/fake/root',
      _gitPull: () => { throw new Error('git pull failed: exit 1'); },
      _rebuildIndex: () => ({ count: 0 }),
      _import:  () => { importCalled = true; },
    }),
    (err) => {
      assert.ok(
        err.message.includes('git pull failed'),
        `expected error to mention 'git pull failed', got: ${err.message}`,
      );
      return true;
    },
  );

  assert.equal(importCalled, false, 'import must NOT be called when git pull fails');
});

// ---------------------------------------------------------------------------
// importMemory (d) exported as a callable function
// ---------------------------------------------------------------------------

test('importMemory is exported as a callable function', () => {
  assert.equal(
    typeof importMemory,
    'function',
    'importMemory must be exported from engram.mjs',
  );
});

// ---------------------------------------------------------------------------
// pullMemory (f) reindex parity (#361) — rebuild the index BETWEEN pull and
// import, in order, with the right recordsDir/indexPath, carrying the
// duplicate accounting out exactly like share()/plainfiles.pull() do.
// ---------------------------------------------------------------------------

test('pullMemory: rebuilds the index between git pull and import, in order (#361 reindex parity)', async () => {
  const calls = [];
  const result = await pullMemory({
    root: '/fake/root',
    _gitPull: () => { calls.push(['pull']); },
    _rebuildIndex: (opts) => { calls.push(['rebuildIndex', opts]); return { count: 7 }; },
    _import: () => { calls.push(['import']); },
  });

  assert.deepEqual(
    calls.map((c) => c[0]),
    ['pull', 'rebuildIndex', 'import'],
    `expected ['pull','rebuildIndex','import'], got ${JSON.stringify(calls.map((c) => c[0]))}`,
  );
  const rebuildOpts = calls[1][1];
  assert.equal(rebuildOpts.recordsDir, '/fake/root/.memory/records');
  assert.equal(rebuildOpts.indexPath, '/fake/root/.memory/index.jsonl');
  assert.deepEqual(result, { indexCount: 7, duplicates: { ids: 0, lines: 0, divergent: 0, groups: [] } });
});

// ---------------------------------------------------------------------------
// pullMemory (g) reindex is unconditional — runs even when the pull was a
// no-op. This is the exact property issue #361 asked for on the `pull`
// verb: `plainfiles.pull()` always reindexes; `pullMemory()` must too,
// never gated on "did git pull bring anything" or "did import write
// anything".
// ---------------------------------------------------------------------------

test('pullMemory: reindexes even on a no-op pull — unconditional, not gated on import having written anything (#361)', async () => {
  let rebuildCalled = false;
  const result = await pullMemory({
    root: '/fake/root',
    _gitPull: () => { /* no-op: already up to date */ },
    _rebuildIndex: () => { rebuildCalled = true; return { count: 0 }; },
    _import: () => ({ written: 0, skipped: 0 }),
  });

  assert.equal(rebuildCalled, true, 'rebuildIndex must run unconditionally, even when nothing changed');
  assert.equal(result.indexCount, 0);
});

// ---------------------------------------------------------------------------
// importMemory (e) pullMemory delegates its import step to importMemory
// ---------------------------------------------------------------------------

test('pullMemory default _import seam is importMemory', async () => {
  // Verify that pullMemory's default _import IS importMemory.
  // We do this structurally: call pullMemory with all other seams mocked,
  // replace _import with a spy, confirm the spy receives the call.
  // Additionally compare that importMemory is the same reference used as default.
  //
  // Since we cannot call the real importMemory without engram installed, we
  // only verify the function reference contract here.
  //
  // Structural guarantee: the default parameter in pullMemory is:
  //   _import = importMemory
  // If this breaks, the test below (e2) would catch it via the call log.
  assert.equal(
    typeof importMemory,
    'function',
    'importMemory must be a function to be a valid default seam',
  );
  // Confirm pullMemory accepts importMemory as _import without error.
  // (Uses other mocked seams to avoid real git/engram calls.)
  let called = false;
  await pullMemory({
    root: '/fake/root',
    _gitPull: () => {},
    _rebuildIndex: () => ({ count: 0 }),
    _import: async () => { called = true; },  // stand-in for importMemory
  });
  assert.ok(called, 'pullMemory must invoke its _import seam (importMemory path)');
});
