// plan.mjs — the pure lane planner (#887 Slice A, ADR-0034 L4/C2).
//
// planLaneCommit() decides, from bytes the shell already read, which
// candidates become the lane commit, which are skipped and why, and what the
// commit's ref/parent/message are. PURE: no `node:fs`, no `child_process`, no
// clock, no `node:os` import — every input arrives as an argument, so the same
// candidate set always yields the same plan (D3's stability obligation) and
// the two invariants this module exists to prove — stability, and
// no-secret-in-the-object-database — are properties of a function, not a
// control-flow claim only a real repo could test. See
// openspec/changes/issue-887-lane-collector/design.md, decisions A1/A5/A6/A7.
//
// A1 — THE PLANNER IS THE SINGLE GATE FOR `skipped`. The shell scans every
// candidate's bytes for secrets and attaches `secret: {pattern, lineNumber}`;
// it does NOT filter. This module routes every non-collectable candidate,
// secret-marked ones included, into `skipped`, and a secret-marked GROUP
// WINNER (chosen by C2 first) skips the whole group — never falls through to
// the runner-up (a secret must never become a selector of record content).
//
// A6 — the C2 tiebreak orders by worktree path using plain code-unit
// comparison (`a < b ? -1 : a > b ? 1 : 0`, duplicates.mjs's own style) —
// NEVER `localeCompare`, which is ICU/locale-dependent and would let the same
// bytes pick different winners on two machines.

import { validateRecord, canonicalOrNull } from '../lib/format.mjs';
import { summarizeDuplicates, emptyDuplicates } from '../lib/duplicates.mjs';

/** Mirrors store.mjs's RECORD_ID_RE/RECORD_MONTH_RE (recordFilename, #677).
 * Not imported from store.mjs — that module carries `node:fs`, and this one
 * must not. A grammar constant, unlike A7's canonicalOrNull, has no logic to
 * drift: both sides state the same regex literally. */
const RECORD_NAME_RE = /^\d{4}-\d{2}-rec-[0-9a-f]{16}\.jsonl$/;

/** The one filename the lane must never treat as a candidate at all — not
 * even reported in `skipped` (L3: derived, regenerated by post-merge). */
const INDEX_FILENAME = 'index.jsonl';

/** ` M` / `M ` / `MM` — a tracked-and-modified record (A8's status map). */
const MODIFIED_STATUSES = new Set([' M', 'M ', 'MM']);

/** L1's ref grammar, asserted against the finished ref before it is returned. */
const REF_GRAMMAR_RE = /^refs\/heads\/memory\/[a-z0-9][a-z0-9-]*-\d{4}-\d{2}-\d{2}$/;

/** The `date` input's own grammar — checked separately from the host slug
 * (E2) so a malformed `date` is never misreported as `memory.collect.badHost`. */
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

/** Plain code-unit comparator — A6, never `localeCompare`. */
function byteCompare(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

/**
 * slugifyHost() — A5: lowercase, every run of `[^a-z0-9]` becomes `-`,
 * collapse repeats, strip leading/trailing `-`, truncate to 40, strip again.
 *
 * Exported (#936, D-sweep step 3): the cross-day sweep (`lane/sweep.mjs`)
 * needs the exact same slug this module already uses to build a ref, so it
 * can filter `memory/<host>-*` refs by an EXACT match on this host's own
 * slug — never a prefix match, which would let a `gandalf` host claim
 * `gandalf-rog-...`'s refs too.
 *
 * @param {string} host
 * @returns {string}
 */
export function slugifyHost(host) {
  let slug = String(host ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '-');
  slug = slug.replace(/^-+|-+$/g, '');
  slug = slug.slice(0, 40);
  slug = slug.replace(/^-+|-+$/g, '');
  return slug;
}

/**
 * parseCandidate() — best-effort JSON.parse of a candidate's content, for
 * validateRecord()/canonicalOrNull() input. Never throws: an unparsable
 * candidate is routed to `invalid` by the caller, not crashed on.
 */
function parseCandidateJson(content) {
  try {
    return JSON.parse(content);
  } catch { /* surfaced: an unparsable candidate reads as undefined and the caller routes it to `invalid` */
    return undefined;
  }
}

/**
 * planLaneCommit() — group candidates by filename, resolve each group by C2,
 * route every non-collectable candidate into `skipped`, and name the commit.
 *
 * @param {{
 *   candidates: Array<{worktree: string, file: string, path: string, status: string,
 *     content: string|null, readError?: string, secret?: {pattern: string, lineNumber: number}}>,
 *   mainPaths: string[],
 *   host: string,
 *   date: string,
 *   parent: {ref: string, tip: string|null},
 * }} input
 * @returns {{ref: string, parent: string, files: Array<{path: string, file: string,
 *   content: string, worktree: string}>, duplicates: object,
 *   skipped: Array<object>, message: string}}
 */
export function planLaneCommit({ candidates, mainPaths, host, date, parent }) {
  const mainSet = new Set(mainPaths);
  const skipped = [];
  /** file (basename) → the candidates that survived classification, awaiting C2. */
  const groups = new Map();

  for (const c of candidates) {
    // L3, belt and braces: never even reported (out of pathspec AND out of grammar).
    if (c.file === INDEX_FILENAME) continue;

    if (!RECORD_NAME_RE.test(c.file)) {
      skipped.push({
        file: c.file,
        worktree: c.worktree,
        reason: 'not-a-record',
        hint: `'${c.file}' does not match the record filename grammar — run \`brain:memory:split-records\` if this is a pre-#677 month log`,
      });
      continue;
    }

    if (c.status === '??') {
      if (mainSet.has(c.path)) {
        skipped.push({ file: c.file, worktree: c.worktree, reason: 'already-on-main' });
        continue;
      }
    } else if (MODIFIED_STATUSES.has(c.status)) {
      skipped.push({ file: c.file, worktree: c.worktree, reason: 'modified-tracked' });
      continue;
    } else {
      skipped.push({ file: c.file, worktree: c.worktree, reason: 'unexpected-status', code: c.status });
      continue;
    }

    if (c.content === null || c.content === undefined) {
      skipped.push({
        file: c.file,
        worktree: c.worktree,
        reason: 'unreadable',
        ...(c.readError !== undefined ? { error: c.readError } : {}),
      });
      continue;
    }

    const parsed = parseCandidateJson(c.content);
    const { valid, errors } = parsed === undefined ? { valid: false, errors: ['invalid JSON'] } : validateRecord(parsed);
    if (!valid) {
      skipped.push({ file: c.file, worktree: c.worktree, reason: 'invalid', errors });
      continue;
    }

    if (!groups.has(c.file)) groups.set(c.file, []);
    groups.get(c.file).push(c);
  }

  const files = [];
  const occurrences = new Map();
  const divergentFiles = new Set();

  const sortedFileKeys = [...groups.keys()].sort(byteCompare);
  for (const file of sortedFileKeys) {
    const group = groups.get(file);
    const sorted = [...group].sort((a, b) => byteCompare(a.worktree, b.worktree));

    // C6: every secret-marked member of the group gets its own skip — winner
    // or loser. A loser that never becomes a selector of record content must
    // still be REPORTED, not silently dropped.
    for (const member of sorted) {
      if (!member.secret) continue;
      skipped.push({
        file,
        worktree: member.worktree,
        reason: 'secret',
        pattern: member.secret.pattern,
        lineNumber: member.secret.lineNumber,
      });
    }

    const winner = sorted[0];
    // C5: a secret-marked winner drops the whole group — never falls through
    // to the runner-up, and the group is never registered as a duplicate (its
    // occurrences are not — and must not become — a fact this run vouches
    // for). Registering occurrences only AFTER this guard is what keeps a
    // secret-skipped group out of `duplicates`.
    if (winner.secret) continue;

    if (sorted.length > 1) {
      occurrences.set(file, sorted.map((g) => `${g.worktree}/${g.path}:1`));
      const canonicals = sorted.map((g) => canonicalOrNull(parseCandidateJson(g.content)));
      const allAgree = canonicals.every((v) => v !== null && v === canonicals[0]);
      if (!allAgree) divergentFiles.add(file);
    }

    files.push({ path: winner.path, file, content: winner.content, worktree: winner.worktree });
  }

  files.sort((a, b) => byteCompare(a.path, b.path));
  skipped.sort((a, b) => byteCompare(a.file, b.file) || byteCompare(a.worktree, b.worktree));

  const duplicates = occurrences.size ? summarizeDuplicates(occurrences, divergentFiles) : emptyDuplicates();

  // E2: validate `date` on its OWN, before it is folded into the ref — a
  // malformed date must never be blamed on the host.
  if (!DATE_RE.test(String(date ?? ''))) {
    throw new Error(`memory.collect.badDate: date ${JSON.stringify(date)} is not YYYY-MM-DD`);
  }

  const hostSlug = slugifyHost(host);
  const ref = `refs/heads/memory/${hostSlug}-${date}`;
  if (!REF_GRAMMAR_RE.test(ref)) {
    throw new Error(`memory.collect.badHost: hostname ${JSON.stringify(host)} slugified to an empty/invalid ref name`);
  }

  const resolvedParent = parent?.tip ? parent.tip : parent?.ref;
  const message = `memory: ${hostSlug} ${date} (${files.length} records)`;

  // E5: no `commit` field — design.md's output shape does not list one, and
  // the shell (collect.mjs) never reads `plan.commit`; it builds its own
  // return object with the real commit sha (or `null` on the no-op path)
  // after running `commit-tree` itself. A static placeholder here would be
  // dead weight this module has no business owning.
  return { ref, parent: resolvedParent, files, duplicates, skipped, message };
}
